title: "The Serial Comma Blog"
description: >- # this means to ignore newlines until "author:"
  Posts from Scott V. Kissinger, the founder of Serial Comma LLC
  on topics related to developing the business and the technology
  behind the business.
author: Scott V. Kissinger
copr_owner: Serial Comma LLC
copr_dates: "2020" # copyright date or date range
github: https://github.com/serialcomma
about: I'm the founder of Serial Comma LLC, a lawyer by trade, and a techie at heart.
# disqus_shortname: # if this is enabled, reactivate code in post.html
# google_analytics: UA-XXXXXXXX-Y

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-github
      link: "https://github.com/serialcomma"
    - icon: fa-twitter
      link: "https://twitter.com/scottkissinger"
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/scottkissingerlawyer/"
#    - icon: fa-facebook
#      link: "#"
#    - icon: fa-stack-exchange
#      link: "#"

share:
  twitter_username: scottkissinger
#   fb_appid: 

urls: # for left column nav
    - text: About Me
      url: /about/
    - text: My Projects
      url: /projects/
    - text: XML Feed
      url: /feed.xml

url: "https://www.serial-comma.com/"
baseurl: "/blog"
port: 4003
permalink: /posts/:name
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
